# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 94f0818e6c5e794e2ffb9792b4a67bcc82abe3f8984277e68d2eb4bcbe86242cab23524ab2f65c5e32ee451337e2504d0c0944733fe0e2efd874396ad6528d6f

test:
  secret_key_base: 5e9e876a19dcf69c9e619ef137b33640f375b49945439a6f76fb79652146f80c00f30402371c7e19febb71f8a3735498b600a47b6157bbc59423cef976f6808b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
